application: tvdb-ical
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /search/.*
  script: tvcal.app

- url: /tvdb-ical/.*
  script: tvcal.app
  
- url: /tvdbimages/.*
  script: tvcal.app

- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /
  static_dir: dist

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^node_modules
- ^test
- ^app
- ^dist/bower_components

libraries:
- name: webapp2
  version: "latest"