application: tvdb-ical
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /search/.*
  script: tvcal.app

- url: /tvdb-ical/.*
  script: tvcal.app
  
- url: /tvdbimages/.*
  script: tvcal.app

- url: /.*
  script: devproxy.app

libraries:
- name: webapp2
  version: "latest"